apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grc
    component: ocm-policy-addon-ctrl
  name: grc-policy-addon-controller
  namespace: multicluster-engine
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grc
      component: ocm-policy-addon-ctrl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grc
        component: ocm-policy-addon-ctrl
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicyaddon
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicyaddon
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - controller
        command:
        - governance-policy-addon-controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CERT_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/cert-policy-controller:2.12.0-SNAPSHOT-2024-09-18-21-46-30
        - name: CONFIG_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/config-policy-controller:2.12.0-SNAPSHOT-2024-09-18-21-46-30
        - name: KUBE_RBAC_PROXY_IMAGE
          value: quay.io/stolostron/kube-rbac-proxy:2.12.0-SNAPSHOT-2024-09-18-21-46-30
        - name: GOVERNANCE_POLICY_FRAMEWORK_ADDON_IMAGE
          value: quay.io/stolostron/governance-policy-framework-addon:2.12.0-SNAPSHOT-2024-09-18-21-46-30
        image: quay.io/stolostron/governance-policy-addon-controller:2.12.0-SNAPSHOT-2024-09-18-21-46-30
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: open-cluster-management-image-pull-credentials
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: grc-policy-addon-sa
      serviceAccountName: grc-policy-addon-sa
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp
