apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: klusterlet-addon-controller-v2
    app.kubernetes.io/name: klusterlet-addon-controller
    component: klusterlet-addon-controller
  name: klusterlet-addon-controller-v2
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: klusterlet-addon-controller-v2
      component: klusterlet-addon-controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: klusterlet-addon-controller-v2
        app.kubernetes.io/name: klusterlet-addon-controller
        component: klusterlet-addon-controller
        ocm-antiaffinity-selector: klusterletaddon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - klusterletaddon
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - klusterletaddon
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: "{{ .Values.global.imageOverrides.klusterlet_addon_controller }}"
        imagePullPolicy: IfNotPresent
        name: klusterlet-addon-controller
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 96Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: open-cluster-management-image-pull-credentials
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: klusterlet-addon-controller-v2
      serviceAccountName: klusterlet-addon-controller-v2
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
